apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: hsvault
  labels:
    "app.kubernetes.io/name": 'vault'
    "helm.sh/chart": "hashicorpvault-1.9.3"
    "app.kubernetes.io/managed-by": "Helm"
    "app.kubernetes.io/instance": "vault"
    "app.kubernetes.io/component": "vault-controller"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: vault
  annotations:
    meta.helm.sh/release-name: 'vault'
    kubernetes.io/ingress.class: external-nginx
    cert-manager.io/cluster-issuer: 'ssl-prod'
    
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: vault
                port:
                  number: 8200
            pathType: ImplementationSpecific
      host: "vault.aws.devops.com.ph"
  tls:
    - hosts:
        - vault.aws.devops.com.ph
      secretName: vault-secret-tls
